# Конфигурация плагина LoggerPunishment
# Плагин логирования игровых наказаний в Discord

# Настройки базы данных
database:
  type: "sqlite" # sqlite или mysql
  
  # Настройки SQLite
  sqlite:
    file: "punishment_logs.db"
  
  # Настройки MySQL
  mysql:
    host: "localhost"
    port: 3306
    database: "minecraft"
    username: "user"
    password: "password"
    
  # Настройки пула соединений HikariCP
  pool:
    maximum_pool_size: 10
    minimum_idle: 2
    connection_timeout: 30000
    idle_timeout: 600000
    max_lifetime: 1800000

# Настройки Discord
discord:
  # Токен бота Discord
  token: "YOUR_DISCORD_BOT_TOKEN"
  
  # ID сервера Discord
  guild_id: 123456789012345678
  
  # ID каналов
  channels:
    players_forum: 123456789012345678      # Форум "Наказания игроков"
    moderators_forum: 123456789012345678   # Форум "Действия модераторов"
    log_channel: 123456789012345678        # Канал "Лог наказаний"
    no_link_notifications: 123456789012345678  # Канал уведомлений о непривязанных аккаунтах
  
  # Настройки сообщений
  messages:
    # Заголовки для разных типов наказаний
    punishment_titles:
      ban: "Блокировка аккаунта"
      mute: "Ограничение чата"
      kick: "Исключение с сервера"
      jail: "Заключение в тюрьму"
    
    # Заголовки для снятия наказаний
    unban_titles:
      unban: "Разблокировка аккаунта"
      unmute: "Снятие ограничения чата"
      unjail: "Освобождение из тюрьмы"
    
    # Цвета embed'ов (hex формат)
    colors:
      ban: "#FF0000"      # Красный
      mute: "#FFA500"     # Оранжевый
      kick: "#FFFF00"     # Желтый
      jail: "#800080"     # Фиолетовый
      unban: "#00FF00"    # Зеленый
      info: "#0099FF"     # Синий
    
    # Эмодзи для различных элементов
    emojis:
      ban: "🚫"
      mute: "🔇"
      kick: "👢"
      jail: "🏢"
      unban: "✅"
      player: "👤"
      moderator: "👮"
      duration: "⏰"
      reason: "📝"
      id: "🆔"
      stats: "📊"
      active: "🔴"
      expired: "⚪"
    
    # Шаблоны сообщений
    templates:
      no_discord_link: |
        🔗 **Игрок не привязал Discord аккаунт**
        
        **Игрок:** {player_name} (`{player_uuid}`)
        **Тип наказания:** {punishment_type}
        **Модератор:** {moderator_name}
        
        Для привязки Discord аккаунта используйте: https://wiki.3b3t.fun/Guides/2FA/

# Настройки Redis
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  timeout: 3000
  
  # Настройки пула соединений
  pool:
    max_active: 20
    max_idle: 10
    min_idle: 5

# API бота аутентификации
auth_bot:
  api_url: "http://localhost:8080/api/v1/discord-link"
  timeout: 5000 # миллисекунды
  retry_attempts: 3
  retry_delay: 1000 # миллисекунды

# Основные настройки плагина
settings:
  # Интервал обновления статистики (секунды)
  stats_update_interval: 30
  
  # Задержка перед удалением неавторизованных сообщений (секунды)
  message_cleanup_delay: 2
  
  # Максимальный размер очереди офлайн действий
  max_queue_size: 1000
  
  # Максимальное время хранения сообщений в очереди (часы)
  queue_message_retention: 24
  
  # Интервал попыток переподключения к Discord (секунды)
  discord_reconnect_interval: 60
  
  # Максимальное количество попыток отправки сообщения
  max_send_attempts: 3
  
  # Задержка между попытками отправки (миллисекунды)
  send_retry_delay: 2000
  
  # Включить режим отладки
  debug_mode: false
  
  # Включить подробное логирование
  verbose_logging: true
  
  # Автоматическое создание резервных копий базы данных
  auto_backup: true
  backup_interval_hours: 24

# Настройки интеграции с плагинами
integrations:
  litebans:
    # Отслеживаемые типы наказаний
    track_bans: true
    track_mutes: true
    track_kicks: true
    track_warnings: false  # Предупреждения не логируем
    
    # Игнорировать временные наказания короче указанного времени (минуты)
    min_temp_duration: 1
  
  cmi:
    # Отслеживание тюремных наказаний
    track_jails: true
    
    # Минимальное время в тюрьме для логирования (минуты)
    min_jail_duration: 5

# Настройки форматирования времени
time_format:
  # Формат отображения даты и времени
  datetime_pattern: "dd.MM.yyyy HH:mm:ss"
  timezone: "Europe/Moscow"
  
  # Локализация единиц времени
  units:
    permanent: "Навсегда"
    years: "г."
    months: "мес."
    days: "д."
    hours: "ч."
    minutes: "мин."
    seconds: "сек."

# Настройки кэширования
cache:
  # Время жизни кэша Discord ID игроков (минуты)
  player_discord_cache_ttl: 60
  
  # Время жизни кэша ID веток форума (минуты)
  thread_cache_ttl: 30
  
  # Время жизни кэша разрешений на отправку сообщений (минуты)
  permissions_cache_ttl: 5
  
  # Размер кэша статистики игроков
  stats_cache_size: 500

# Версия конфигурации (не изменять)
config_version: 1 